Repository fluttercommunity/plus_plugins, pull requests merged in 2021-10, with the labels that each got.

#458 [share_plus] Use NSURL for web links
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
  packages/share_plus/share_plus/pubspec.yaml
Labels: Hacktoberfest

#466 migrate integration_test to flutter sdk
  packages/android_alarm_manager_plus/CHANGELOG.md
  packages/android_alarm_manager_plus/pubspec.yaml
  packages/android_intent_plus/CHANGELOG.md
  packages/android_intent_plus/example/pubspec.yaml
  packages/android_intent_plus/pubspec.yaml
  packages/battery_plus/battery_plus/CHANGELOG.md
  packages/battery_plus/battery_plus/example/pubspec.yaml
  packages/battery_plus/battery_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/example/pubspec.yaml
  packages/device_info_plus/device_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/example/pubspec.yaml
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/package_info_plus/package_info_plus/CHANGELOG.md
  packages/package_info_plus/package_info_plus/example/pubspec.yaml
  packages/package_info_plus/package_info_plus/pubspec.yaml
  packages/sensors_plus/sensors_plus/CHANGELOG.md
  packages/sensors_plus/sensors_plus/example/pubspec.yaml
  packages/sensors_plus/sensors_plus/pubspec.yaml
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus/pubspec.yaml
  packages/share_plus/share_plus_web/integration_test/pubspec.yaml
Labels: Hacktoberfest

#451 [network_info_plus] Fix issue #431 network_info_plus: 'net/route.h' file not found when building for iOS emulator
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/ios/Classes/getgateway.c
  packages/network_info_plus/network_info_plus/pubspec.yaml
Labels: Hacktoberfest

#472 [package_info_plus] fix app name on iOS and macOS
  packages/package_info_plus/package_info_plus/CHANGELOG.md
  packages/package_info_plus/package_info_plus/ios/Classes/FLTPackageInfoPlusPlugin.m
  packages/package_info_plus/package_info_plus/pubspec.yaml
  packages/package_info_plus/package_info_plus_macos/CHANGELOG.md
  packages/package_info_plus/package_info_plus_macos/macos/Classes/FLTPackageInfoPlusPlugin.m
  packages/package_info_plus/package_info_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#492 docs: fix few directory paths on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#491 [package_info_plus] annotate int for flutter 2.5 requirement
  packages/package_info_plus/package_info_plus/CHANGELOG.md
  packages/package_info_plus/package_info_plus/pubspec.yaml
  packages/package_info_plus/package_info_plus_windows/CHANGELOG.md
  packages/package_info_plus/package_info_plus_windows/lib/src/file_version_info.dart
  packages/package_info_plus/package_info_plus_windows/pubspec.yaml
Labels: package_info_plus, Hacktoberfest, hacktoberfest-accepted

#463 [connectivity_plus_windows] add ethernet support
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_windows/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_windows/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_windows/windows/CMakeLists.txt
  packages/connectivity_plus/connectivity_plus_windows/windows/connectivity_plus_windows_plugin.cpp
  packages/connectivity_plus/connectivity_plus_windows/windows/include/connectivity_plus_windows/network_manager.h
  packages/connectivity_plus/connectivity_plus_windows/windows/network_manager.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#486 Fix alarm_manager_plus for Android 12+
  packages/android_alarm_manager_plus/CHANGELOG.md
  packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java
  packages/android_alarm_manager_plus/pubspec.yaml
Labels: android_alarm_manager_plus, Hacktoberfest, hacktoberfest-accepted

#473 [network_info_plus] ios: handle deprecation of `CNCopyCurrentNetworkInfo`
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/ios/Classes/FLTCaptiveNetworkInfoProvider.h
  packages/network_info_plus/network_info_plus/ios/Classes/FLTCaptiveNetworkInfoProvider.m
  packages/network_info_plus/network_info_plus/ios/Classes/FLTHotspotNetworkInfoProvider.h
  packages/network_info_plus/network_info_plus/ios/Classes/FLTHotspotNetworkInfoProvider.m
  packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfo.h
  packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfo.m
  packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m
  packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoProvider.h
  packages/network_info_plus/network_info_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#470 [connectivity_plus_macos] backport to macOS 10.11
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/example/macos/Runner.xcodeproj/project.pbxproj
  packages/connectivity_plus/connectivity_plus/macos/connectivity_plus.podspec
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ConnectivityPlugin.swift
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/PathMonitorConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ReachabilityConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/macos/connectivity_plus_macos.podspec
  packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#489 Update Melos and CD/CI
  .github/_backup/android_alarm_manager_plus.yaml
  .github/_backup/android_intent_plus.yaml
  .github/_backup/battery_plus.yaml
  .github/_backup/connectivity_plus.yaml
  .github/_backup/device_info_plus.yaml
  .github/_backup/network_info_plus.yaml
  .github/_backup/package_info_plus.yaml
  .github/_backup/sensors_plus.yaml
  .github/_backup/share_plus.yaml
  .github/workflows/all_plugins.yaml
  .github/workflows/scripts/build-examples.sh
  .github/workflows/scripts/drive-example.sh
  .github/workflows/scripts/install-flutter.sh
  .github/workflows/scripts/install-tools.sh
  melos.yaml
  packages/sensors_plus/sensors_plus/test/sensors_test.dart
  packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart
  packages/sensors_plus/sensors_plus_web/test/sensors_plus_web_test.dart
  packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
Labels: enhancement, CD/CI, Hacktoberfest

#494 fix(android_alarm_manger_plus): Build issues due to missing imports
  packages/android_alarm_manager_plus/CHANGELOG.md
  packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java
  packages/android_alarm_manager_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#495 Remove deprecated registerWith method of Android v1 embedding
  packages/android_intent_plus/CHANGELOG.md
  packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/AndroidIntentPlugin.java
  packages/android_intent_plus/pubspec.yaml
  packages/battery_plus/battery_plus/CHANGELOG.md
  packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
  packages/battery_plus/battery_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityPlugin.java
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java
  packages/device_info_plus/device_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfoPlusPlugin.java
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/android/src/main/java/dev/fluttercommunity/plus/share/SharePlusPlugin.java
  packages/share_plus/share_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#500 [network_info_plus] Implemented get ip v6 macos
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/example/macos/Runner.xcodeproj/project.pbxproj
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus_macos/CHANGELOG.md
  packages/network_info_plus/network_info_plus_macos/macos/Classes/IPHelper.h
  packages/network_info_plus/network_info_plus_macos/macos/Classes/NetworkInfoPlusPlugin.swift
  packages/network_info_plus/network_info_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#496 fix(android_alarm_manger_plus): Periodic alarm becomes inexact after some time
  packages/android_alarm_manager_plus/CHANGELOG.md
  packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java
  packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java
  packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart
  packages/android_alarm_manager_plus/test/android_alarm_manager_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#444 [connectivity_plus] Remove unused IPHelper file
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/IPHelper.h
Labels: Hacktoberfest, hacktoberfest-accepted

#502 Update (android_alarm_manager_plus): Bump targetSDK to 30, update Android related dependencies
  packages/android_alarm_manager_plus/CHANGELOG.md
  packages/android_alarm_manager_plus/android/build.gradle
  packages/android_alarm_manager_plus/android/gradle.properties
  packages/android_alarm_manager_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/android_alarm_manager_plus/example/android/app/build.gradle
  packages/android_alarm_manager_plus/example/android/build.gradle
  packages/android_alarm_manager_plus/example/android/gradle.properties
  packages/android_alarm_manager_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/android_alarm_manager_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#507 fix(android_intent_plus): Remove embedding v1 reference & update dependencies
  packages/android_intent_plus/CHANGELOG.md
  packages/android_intent_plus/android/build.gradle
  packages/android_intent_plus/android/src/main/AndroidManifest.xml
  packages/android_intent_plus/example/android/app/build.gradle
  packages/android_intent_plus/example/android/app/src/androidTestDebug/java/io/flutter/plugins/androidintentexample/EmbeddingV1ActivityTest.java
  packages/android_intent_plus/example/android/app/src/main/AndroidManifest.xml
  packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/EmbeddingV1Activity.java
  packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/MainActivity.java
  packages/android_intent_plus/example/android/build.gradle
  packages/android_intent_plus/example/android/gradle.properties
  packages/android_intent_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/android_intent_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#508 fix(battery_plus): Upgrade gradle, android compile version & implement code improvements
  packages/battery_plus/battery_plus/CHANGELOG.md
  packages/battery_plus/battery_plus/android/build.gradle
  packages/battery_plus/battery_plus/android/src/main/AndroidManifest.xml
  packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
  packages/battery_plus/battery_plus/example/android/app/build.gradle
  packages/battery_plus/battery_plus/example/android/app/src/main/AndroidManifest.xml
  packages/battery_plus/battery_plus/example/android/app/src/main/kotlin/io/flutter/plugins/batteryexample/example/MainActivity.kt
  packages/battery_plus/battery_plus/example/android/build.gradle
  packages/battery_plus/battery_plus/example/android/gradle.properties
  packages/battery_plus/battery_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/battery_plus/battery_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#510 fix(connectivity_plus): Upgrade gradle, android compile version & implement code improvements
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/android/build.gradle
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityMethodChannelHandler.java
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityPlugin.java
  packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
  packages/connectivity_plus/connectivity_plus/example/android/app/src/main/AndroidManifest.xml
  packages/connectivity_plus/connectivity_plus/example/android/app/src/main/java/io/flutter/plugins/connectivityexample/EmbeddingV1Activity.java
  packages/connectivity_plus/connectivity_plus/example/android/app/src/main/java/io/flutter/plugins/connectivityexample/EmbeddingV1ActivityTest.java
  packages/connectivity_plus/connectivity_plus/example/android/build.gradle
  packages/connectivity_plus/connectivity_plus/example/android/gradle.properties
  packages/connectivity_plus/connectivity_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#509 fix(share_plus): Bump Android dependencies, remove embedding V1 from example
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/example/android/app/build.gradle
  packages/share_plus/share_plus/example/android/app/src/main/AndroidManifest.xml
  packages/share_plus/share_plus/example/android/app/src/main/java/io/flutter/plugins/shareexample/EmbeddingV1Activity.java
  packages/share_plus/share_plus/example/android/app/src/main/java/io/flutter/plugins/shareexample/EmbeddingV1ActivityTest.java
  packages/share_plus/share_plus/example/android/app/src/main/java/io/flutter/plugins/shareexample/FlutterActivityTest.java
  packages/share_plus/share_plus/example/android/build.gradle
  packages/share_plus/share_plus/example/android/gradle.properties
  packages/share_plus/share_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#511 fix(device_info_plus): Upgrade gradle, android compile version & implement code improvements
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/android/build.gradle
  packages/device_info_plus/device_info_plus/android/src/main/AndroidManifest.xml
  packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java
  packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
  packages/device_info_plus/device_info_plus/example/android/app/build.gradle
  packages/device_info_plus/device_info_plus/example/android/app/src/main/AndroidManifest.xml
  packages/device_info_plus/device_info_plus/example/android/app/src/main/kotlin/io/flutter/plugins/deviceinfoexample/example/MainActivity.kt
  packages/device_info_plus/device_info_plus/example/android/build.gradle
  packages/device_info_plus/device_info_plus/example/android/gradle.properties
  packages/device_info_plus/device_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/device_info_plus/device_info_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#512 fix(network_info_plus): Upgrade gradle, android compile version & implement code improvements
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/README.md
  packages/network_info_plus/network_info_plus/android/build.gradle
  packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfo.java
  packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfoMethodChannelHandler.java
  packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfoPlusPlugin.java
  packages/network_info_plus/network_info_plus/example/android/app/build.gradle
  packages/network_info_plus/network_info_plus/example/android/app/src/main/AndroidManifest.xml
  packages/network_info_plus/network_info_plus/example/android/app/src/main/java/dev/fluttercommunity/plus/network_info_plus_example/EmbeddingV1Activity.java
  packages/network_info_plus/network_info_plus/example/android/app/src/main/java/dev/fluttercommunity/plus/network_info_plus_example/EmbeddingV1ActivityTest.java
  packages/network_info_plus/network_info_plus/example/android/build.gradle
  packages/network_info_plus/network_info_plus/example/android/gradle.properties
  packages/network_info_plus/network_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/network_info_plus/network_info_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#442 fix(package_info_plus): fixed deprecation warning & updated dependencies
  packages/package_info_plus/package_info_plus/CHANGELOG.md
  packages/package_info_plus/package_info_plus/android/build.gradle
  packages/package_info_plus/package_info_plus/android/src/main/AndroidManifest.xml
  packages/package_info_plus/package_info_plus/android/src/main/java/dev/fluttercommunity/plus/packageinfo/PackageInfoPlugin.java
  packages/package_info_plus/package_info_plus/example/android/app/build.gradle
  packages/package_info_plus/package_info_plus/example/android/app/src/main/AndroidManifest.xml
  packages/package_info_plus/package_info_plus/example/android/app/src/main/java/io/flutter/plugins/packageinfoexample/EmbedderV1Activity.java
  packages/package_info_plus/package_info_plus/example/android/build.gradle
  packages/package_info_plus/package_info_plus/example/android/gradle.properties
  packages/package_info_plus/package_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/package_info_plus/package_info_plus/example/android/settings.gradle
  packages/package_info_plus/package_info_plus/example/pubspec.yaml
  packages/package_info_plus/package_info_plus/example/test_driver/package_info_plus_e2e.dart
  packages/package_info_plus/package_info_plus/example/test_driver/package_info_plus_e2e_test.dart
  packages/package_info_plus/package_info_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#515 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Hacktoberfest, hacktoberfest-accepted

#521 fix(connectivity_plus): fix lambda not supported error.
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/android/build.gradle
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#520 Update CONTRIBUTING on types of contributions
  CONTRIBUTING.md
Labels: Hacktoberfest, hacktoberfest-accepted
