Repository fluttercommunity/plus_plugins, pull requests merged in 2021-11, with the labels that each got.

#585 fix(android_intent_plus): fixed a bug!
  packages/android_intent_plus/CHANGELOG.md
  packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
  packages/android_intent_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#586 [battery_plus_linux] rename plugin class
  packages/battery_plus/battery_plus_linux/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#587 [examples] explicitly override deps
  packages/battery_plus/battery_plus/example/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
  packages/device_info_plus/device_info_plus/example/pubspec.yaml
  packages/network_info_plus/network_info_plus/example/pubspec.yaml
  packages/package_info_plus/package_info_plus/example/pubspec.yaml
  packages/sensors_plus/sensors_plus/example/pubspec.yaml
  packages/share_plus/share_plus/example/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#588 [device_info_plus_macos] fix compiler warnings
  packages/device_info_plus/device_info_plus_macos/macos/Classes/DeviceInfoPlusMacosPlugin.swift
Labels: Hacktoberfest, hacktoberfest-accepted

#590 [CI] Add missing melos bootstrap
  .github/workflows/all_plugins.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#595 [battery_plus_linux] get rid of the _real vs. _stub hack
  packages/battery_plus/battery_plus_linux/lib/battery_plus_linux.dart
  packages/battery_plus/battery_plus_linux/lib/src/battery_plus_linux.dart
  packages/battery_plus/battery_plus_linux/lib/src/battery_plus_linux_stub.dart
  packages/battery_plus/battery_plus_linux/test/battery_plus_linux_test.dart
Labels: battery_plus, linux

#596 [connectivity_plus_linux] get rid of the _real vs. _stub hack
  packages/connectivity_plus/connectivity_plus_linux/lib/connectivity_plus_linux.dart
  packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity.dart
  packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity_stub.dart
  packages/connectivity_plus/connectivity_plus_linux/test/connectivity_plus_linux_test.dart
Labels: connectivity_plus, linux

#597 [network_info_plus_linux] get rid of the _real vs. _stub hack
  packages/network_info_plus/network_info_plus_linux/lib/network_info_plus_linux.dart
  packages/network_info_plus/network_info_plus_linux/lib/src/network_info.dart
  packages/network_info_plus/network_info_plus_linux/lib/src/network_info_stub.dart
  packages/network_info_plus/network_info_plus_linux/test/device_info_plus_linux_test.dart
Labels: network_info_plus, linux

#598 [device_info_plus_windows] get rid of the _real vs. _stub hack
  packages/device_info_plus/device_info_plus_windows/lib/device_info_plus_windows.dart
  packages/device_info_plus/device_info_plus_windows/lib/src/device_info_plus_windows.dart
  packages/device_info_plus/device_info_plus_windows/lib/src/device_info_plus_windows_stub.dart
  packages/device_info_plus/device_info_plus_windows/test/device_info_plus_test.dart
Labels: device_info_plus, windows

#599 [package_info_plus_windows] get rid of the _real vs. _stub hack
  packages/package_info_plus/package_info_plus_windows/lib/package_info_plus_windows.dart
  packages/package_info_plus/package_info_plus_windows/lib/src/package_info_plus_windows.dart
  packages/package_info_plus/package_info_plus_windows/lib/src/package_info_plus_windows_stub.dart
  packages/package_info_plus/package_info_plus_windows/test/package_info_plus_windows_test.dart
Labels: package_info_plus, windows

#571 [network_info_plus_macos] more info
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus_macos/CHANGELOG.md
  packages/network_info_plus/network_info_plus_macos/macos/Classes/NetworkInfoPlusPlugin.swift
  packages/network_info_plus/network_info_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#593 feat(device_info_plus): add toMap method to WebBrowserInfo
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/lib/device_info_plus.dart
  packages/device_info_plus/device_info_plus/pubspec.yaml
  packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
  packages/device_info_plus/device_info_plus_platform_interface/lib/model/web_browser_info.dart
  packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
  packages/device_info_plus/device_info_plus_platform_interface/test/model/web_browser_info_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted
