Repository fluttercommunity/plus_plugins, pull requests merged in 2022-10, with the labels that each got.

#1121 corrected BSD-3-Clause License
  packages/android_intent_plus/LICENSE
Labels: Hacktoberfest, hacktoberfest-accepted

#1120 [Battery_plus] Fix: batteryState always return unknown on API < 26
  packages/battery_plus/battery_plus/CHANGELOG.md
  packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt
  packages/battery_plus/battery_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1116 [Github Actions] Add ignored paths for Build website preview workflow
  .github/workflows/build_preview_website.yaml
Labels: CI/CD, Hacktoberfest, hacktoberfest-accepted

#1127 fixed broken 'Edit this page' Link in the Website
  website/docusaurus.config.js
Labels: Hacktoberfest, hacktoberfest-accepted

#1130 fix [docs]: Replace pub score badges, update project README
  README.md
  packages/android_alarm_manager_plus/README.md
  packages/android_intent_plus/README.md
  packages/battery_plus/battery_plus/README.md
  packages/connectivity_plus/connectivity_plus/README.md
  packages/device_info_plus/device_info_plus/README.md
  packages/network_info_plus/network_info_plus/README.md
  packages/package_info_plus/package_info_plus/README.md
  packages/sensors_plus/sensors_plus/README.md
  packages/share_plus/share_plus/README.md
Labels: documentation, all, Hacktoberfest, hacktoberfest-accepted

#1133 Setup Windows CI process
  .github/workflows/battery_plus.yaml
  .github/workflows/connectivity_plus.yaml
  .github/workflows/device_info_plus.yaml
  .github/workflows/network_info_plus.yaml
  .github/workflows/package_info_plus.yaml
  .github/workflows/scripts/build-examples.sh
  .github/workflows/scripts/install-tools.sh
  .github/workflows/scripts/integration-test.sh
  .github/workflows/share_plus.yaml
  packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart
  packages/package_info_plus/package_info_plus/example/.metadata
  packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
  packages/package_info_plus/package_info_plus/example/windows/CMakeLists.txt
  packages/package_info_plus/package_info_plus/example/windows/flutter/CMakeLists.txt
  packages/package_info_plus/package_info_plus/example/windows/runner/CMakeLists.txt
  packages/package_info_plus/package_info_plus/example/windows/runner/Runner.rc
  packages/package_info_plus/package_info_plus/example/windows/runner/flutter_window.cpp
  packages/package_info_plus/package_info_plus/example/windows/runner/flutter_window.h
  packages/package_info_plus/package_info_plus/example/windows/runner/main.cpp
  packages/package_info_plus/package_info_plus/example/windows/runner/resource.h
  packages/package_info_plus/package_info_plus/example/windows/runner/run_loop.cpp
  packages/package_info_plus/package_info_plus/example/windows/runner/run_loop.h
  packages/package_info_plus/package_info_plus/example/windows/runner/runner.exe.manifest
  packages/package_info_plus/package_info_plus/example/windows/runner/utils.cpp
  packages/package_info_plus/package_info_plus/example/windows/runner/utils.h
  packages/package_info_plus/package_info_plus/example/windows/runner/win32_window.cpp
  packages/package_info_plus/package_info_plus/example/windows/runner/win32_window.h
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest-Special

#1126 Enable Integration tests for MacOS
  .github/workflows/battery_plus.yaml
  .github/workflows/connectivity_plus.yaml
  .github/workflows/device_info_plus.yaml
  .github/workflows/network_info_plus.yaml
  .github/workflows/package_info_plus.yaml
  .github/workflows/share_plus.yaml
  packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart
  packages/battery_plus/battery_plus/lib/battery_plus.dart
  packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
  packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
  packages/share_plus/share_plus/example/integration_test/share_plus_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest-Special

#1136 [android_intent_plus] Fix fallback to implicit intent
  packages/android_intent_plus/CHANGELOG.md
  packages/android_intent_plus/android/build.gradle
  packages/android_intent_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
  packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
  packages/android_intent_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/android_intent_plus/example/android/build.gradle
  packages/android_intent_plus/example/android/gradle.properties
  packages/android_intent_plus/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/android_intent_plus/pubspec.yaml
Labels: android_intent_plus, Hacktoberfest, hacktoberfest-accepted

#1128 [website] Fixed admonitions
  website/src/theme/MDXComponents/index.tsx
Labels: website, Hacktoberfest, hacktoberfest-accepted

#1147 Tb/feature/cancel previous jobs based on github ref
  .github/workflows/all_plugins.yaml
  .github/workflows/android_alarm_manager_plus.yaml
  .github/workflows/android_intent_plus.yaml
  .github/workflows/battery_plus.yaml
  .github/workflows/build_deploy_website.yaml
  .github/workflows/build_preview_website.yaml
  .github/workflows/connectivity_plus.yaml
  .github/workflows/device_info_plus.yaml
  .github/workflows/network_info_plus.yaml
  .github/workflows/package_info_plus.yaml
  .github/workflows/sensors_plus.yaml
  .github/workflows/share_plus.yaml
  .github/workflows/stale.yml
Labels: Hacktoberfest, hacktoberfest-accepted

#1144 [connectivity_plus] discard unused result warning for method calls
  packages/connectivity_plus/connectivity_plus/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus/ios/Classes/PathMonitorConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus/ios/Classes/ReachabilityConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/PathMonitorConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ReachabilityConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1137 [linux test integration] - run Linux tests in CI 1104
  .github/workflows/battery_plus.yaml
  .github/workflows/connectivity_plus.yaml
  .github/workflows/device_info_plus.yaml
  .github/workflows/network_info_plus.yaml
  .github/workflows/package_info_plus.yaml
  .github/workflows/scripts/integration-test.sh
  .github/workflows/share_plus.yaml
  packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart
  packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
  packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
  packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest-Special

#1148 [device_info_plus] Detect iOS simulator model identifier
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
  packages/device_info_plus/device_info_plus/ios/Classes/FLTDeviceInfoPlusPlugin.m
  packages/device_info_plus/device_info_plus/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1154 [connectivity_plus] discard unused warnings for `switch reachability.connection ?? .unavailable` in macOS
  packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ReachabilityConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1151 [network_info_plus] Use new Android APIs
  docs/network_info_plus/usage.mdx
  packages/network_info_plus/network_info_plus/CHANGELOG.md
  packages/network_info_plus/network_info_plus/README.md
  packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfo.kt
  packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfoPlusPlugin.kt
  packages/network_info_plus/network_info_plus/example/android/app/src/main/AndroidManifest.xml
  packages/network_info_plus/network_info_plus/example/lib/main.dart
  packages/network_info_plus/network_info_plus/pubspec.yaml
Labels: network_info_plus, Hacktoberfest, hacktoberfest-accepted

#1153 [share_plus] Enable Web implementations for `shareFiles`
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/README.md
  packages/share_plus/share_plus/example/lib/image_previews.dart
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/lib/share_plus.dart
  packages/share_plus/share_plus/pubspec.yaml
  packages/share_plus/share_plus_platform_interface/CHANGELOG.md
  packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
  packages/share_plus/share_plus_platform_interface/lib/share_plus_platform_interface.dart
  packages/share_plus/share_plus_platform_interface/pubspec.yaml
  packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
  packages/share_plus/share_plus_web/CHANGELOG.md
  packages/share_plus/share_plus_web/lib/share_plus_web.dart
  packages/share_plus/share_plus_web/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest-Special

#1157 [share_plus] Remove usage of deprecated UIApplication.keyWindow in iOS 13+
  packages/share_plus/share_plus/CHANGELOG.md
  packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
Labels: Hacktoberfest, hacktoberfest-accepted

#1156 [device_info_plus] feat: more info for Windows (re-land #814)
  packages/device_info_plus/device_info_plus/CHANGELOG.md
  packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
  packages/device_info_plus/device_info_plus/example/lib/main.dart
  packages/device_info_plus/device_info_plus/pubspec.yaml
  packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
  packages/device_info_plus/device_info_plus_platform_interface/lib/model/windows_device_info.dart
  packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
  packages/device_info_plus/device_info_plus_platform_interface/test/model/windows_device_info_test.dart
  packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
  packages/device_info_plus/device_info_plus_windows/lib/src/device_info_plus_windows.dart
  packages/device_info_plus/device_info_plus_windows/pubspec.yaml
  packages/device_info_plus/device_info_plus_windows/test/device_info_plus_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1158 feat(share_plus)!: Native share UI for Windows
  .github/workflows/share_plus.yaml
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/example/lib/utils/file_picker_web.dart
  packages/share_plus/share_plus/example/lib/utils/file_picker_win.dart
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus_windows/.clang-format
  packages/share_plus/share_plus_windows/lib/share_plus_windows.dart
  packages/share_plus/share_plus_windows/lib/src/version_helper.dart
  packages/share_plus/share_plus_windows/pubspec.yaml
  packages/share_plus/share_plus_windows/test/share_plus_windows_test.dart
  packages/share_plus/share_plus_windows/windows/.gitignore
  packages/share_plus/share_plus_windows/windows/CMakeLists.txt
  packages/share_plus/share_plus_windows/windows/include/share_plus_windows/share_plus_windows_plugin_c_api.h
  packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin.cpp
  packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin.h
  packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin_c_api.cpp
  packages/share_plus/share_plus_windows/windows/vector.h
Labels: Hacktoberfest, hacktoberfest-accepted

#1163 test(android_alarm_manager_plus): Add integration tests to alarm manager
  .github/workflows/android_alarm_manager_plus.yaml
  packages/android_alarm_manager_plus/example/integration_test/android_alarm_manager_plus_test.dart
  packages/android_alarm_manager_plus/example/lib/main.dart
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest-Special

#1174 feat(connectivity_plus): vpn support for android and linux
  packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
  packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity.dart
  packages/connectivity_plus/connectivity_plus_linux/test/connectivity_plus_linux_test.dart
  packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/enums.dart
  packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/utils.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1179 docs(android_intent_plus): Add documentation for canResolveActivity
  packages/android_intent_plus/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#1135 feat(package_info_plus)!: Add information about the installer store
  packages/package_info_plus/package_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/packageinfo/PackageInfoPlugin.kt
  packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
  packages/package_info_plus/package_info_plus/example/lib/main.dart
  packages/package_info_plus/package_info_plus/ios/Classes/FLTPackageInfoPlusPlugin.m
  packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
  packages/package_info_plus/package_info_plus/test/package_info_test.dart
  packages/package_info_plus/package_info_plus_macos/macos/Classes/FLTPackageInfoPlusPlugin.m
  packages/package_info_plus/package_info_plus_platform_interface/CHANGELOG.md
  packages/package_info_plus/package_info_plus_platform_interface/lib/method_channel_package_info.dart
  packages/package_info_plus/package_info_plus_platform_interface/lib/package_info_data.dart
  packages/package_info_plus/package_info_plus_platform_interface/test/method_channel_package_info_test.dart
  packages/package_info_plus/package_info_plus_web/test/package_info_plus_web_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1182 docs: Use correct command to activate Melos
  CONTRIBUTING.md
Labels: documentation

#1186 fix(share_plus): Share.shareXFiles resulting in stack-overflow on Windows & Linux
  packages/share_plus/share_plus_linux/lib/share_plus_linux.dart
  packages/share_plus/share_plus_linux/pubspec.yaml
  packages/share_plus/share_plus_windows/lib/share_plus_windows.dart
  packages/share_plus/share_plus_windows/lib/src/version_helper.dart
  packages/share_plus/share_plus_windows/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1184 ci(android_alarm_manager_plus): Add matrix of versions for integration tests
  .github/workflows/android_alarm_manager_plus.yaml
Labels: android_alarm_manager_plus, CI/CD

#1155 fix(network_info_plus): Mark iOS-specific permission methods as deprecated and update docs
  packages/network_info_plus/network_info_plus/README.md
  packages/network_info_plus/network_info_plus/lib/network_info_plus.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1189 ci: Update checkout actions
  .github/workflows/all_plugins.yaml
  .github/workflows/build_deploy_website.yaml
Labels: CI/CD

#1223 fix(share_plus): Show NSSharingServicePicker asynchronously on main thread
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/example/lib/utils/file_picker_web.dart
  packages/share_plus/share_plus/example/lib/utils/file_picker_win.dart
  packages/share_plus/share_plus/example/macos/Runner/DebugProfile.entitlements
  packages/share_plus/share_plus/example/macos/Runner/Release.entitlements
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus_macos/macos/Classes/SharePlusMacosPlugin.swift
Labels: Hacktoberfest, hacktoberfest-accepted

#1229 docs(android_alarm_manager_plus): Fix example and docs to explain required annotation
  docs/android_alarm_manager_plus/usage.mdx
  packages/android_alarm_manager_plus/README.md
  packages/android_alarm_manager_plus/example/lib/main.dart
Labels: documentation, android_alarm_manager_plus

#1231 fix(network_info_plus): Get SSID on Android 12 and newer
  packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfo.kt
Labels: network_info_plus, hacktoberfest-accepted

#1227 refactor(connectivity_plus)!: two-package federated architecture
  packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
  packages/connectivity_plus/connectivity_plus/example/lib/main.dart
  packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/lib/connectivity_plus.dart
  packages/connectivity_plus/connectivity_plus/lib/src/connectivity_plus_linux.dart
  packages/connectivity_plus/connectivity_plus/lib/src/connectivity_plus_web.dart
  packages/connectivity_plus/connectivity_plus/lib/src/web/dart_html_connectivity_plugin.dart
  packages/connectivity_plus/connectivity_plus/lib/src/web/network_information_api_connectivity_plugin.dart
  packages/connectivity_plus/connectivity_plus/lib/src/web/utils/connectivity_result.dart
  packages/connectivity_plus/connectivity_plus/macos/Classes/ConnectivityPlugin.swift
  packages/connectivity_plus/connectivity_plus/macos/Classes/ConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus/macos/Classes/PathMonitorConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus/macos/Classes/ReachabilityConnectivityProvider.swift
  packages/connectivity_plus/connectivity_plus/macos/connectivity_plus.podspec
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/test/connectivity_plus_linux_test.dart
  packages/connectivity_plus/connectivity_plus/test/connectivity_plus_linux_test.mocks.dart
  packages/connectivity_plus/connectivity_plus/windows/.gitignore
  packages/connectivity_plus/connectivity_plus/windows/CMakeLists.txt
  packages/connectivity_plus/connectivity_plus/windows/connectivity_plus_plugin.cpp
  packages/connectivity_plus/connectivity_plus/windows/include/connectivity_plus/connectivity_plus_windows_plugin.h
  packages/connectivity_plus/connectivity_plus/windows/include/connectivity_plus/network_manager.h
  packages/connectivity_plus/connectivity_plus/windows/network_manager.cpp
  packages/connectivity_plus/connectivity_plus_linux/.gitignore
  packages/connectivity_plus/connectivity_plus_linux/.metadata
  packages/connectivity_plus/connectivity_plus_linux/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_linux/LICENSE
  packages/connectivity_plus/connectivity_plus_linux/README.md
  packages/connectivity_plus/connectivity_plus_linux/lib/connectivity_plus_linux.dart
  packages/connectivity_plus/connectivity_plus_linux/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_macos/.gitattributes
  packages/connectivity_plus/connectivity_plus_macos/.gitignore
  packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_macos/LICENSE
  packages/connectivity_plus/connectivity_plus_macos/README.md
  packages/connectivity_plus/connectivity_plus_macos/lib/connectivity_plus_macos.dart
  packages/connectivity_plus/connectivity_plus_macos/macos/connectivity_plus_macos.podspec
  packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_web/.gitattributes
  packages/connectivity_plus/connectivity_plus_web/.gitignore
  packages/connectivity_plus/connectivity_plus_web/.metadata
  packages/connectivity_plus/connectivity_plus_web/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_web/LICENSE
  packages/connectivity_plus/connectivity_plus_web/README.md
  packages/connectivity_plus/connectivity_plus_web/example/.gitignore
  packages/connectivity_plus/connectivity_plus_web/example/lib/main.dart
  packages/connectivity_plus/connectivity_plus_web/example/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_web/example/test_driver/README.md
  packages/connectivity_plus/connectivity_plus_web/example/test_driver/connectivity_plus_example.dart
  packages/connectivity_plus/connectivity_plus_web/example/test_driver/connectivity_plus_example_test.dart
  packages/connectivity_plus/connectivity_plus_web/example/test_driver/src/connectivity_mocks.dart
  packages/connectivity_plus/connectivity_plus_web/example/web/index.html
  packages/connectivity_plus/connectivity_plus_web/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_windows/.gitignore
  packages/connectivity_plus/connectivity_plus_windows/.metadata
  packages/connectivity_plus/connectivity_plus_windows/CHANGELOG.md
  packages/connectivity_plus/connectivity_plus_windows/LICENSE
  packages/connectivity_plus/connectivity_plus_windows/README.md
  packages/connectivity_plus/connectivity_plus_windows/lib/connectivity_plus_windows.dart
  packages/connectivity_plus/connectivity_plus_windows/pubspec.yaml
Labels: hacktoberfest-accepted

#1233 fix(all): lint warnings - add missing dependency for tests
  packages/android_alarm_manager_plus/example/lib/main_espresso.dart
  packages/android_intent_plus/example/pubspec.yaml
  packages/battery_plus/battery_plus/example/lib/main.dart
  packages/battery_plus/battery_plus/example/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
  packages/network_info_plus/network_info_plus/example/pubspec.yaml
  packages/sensors_plus/sensors_plus/example/pubspec.yaml
  packages/share_plus/share_plus/example/pubspec.yaml
Labels: hacktoberfest-accepted

#1239 ci(all): Add Android build matrix for all plugins
  .github/workflows/android_intent_plus.yaml
  .github/workflows/battery_plus.yaml
  .github/workflows/connectivity_plus.yaml
  .github/workflows/device_info_plus.yaml
  .github/workflows/network_info_plus.yaml
  .github/workflows/package_info_plus.yaml
  .github/workflows/sensors_plus.yaml
  .github/workflows/share_plus.yaml
Labels: CI/CD, Hacktoberfest, hacktoberfest-accepted

#1238 refactor(share_plus)!: two-package federated architecture
  packages/share_plus/share_plus/example/ios/Flutter/Flutter.podspec
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus/lib/share_plus.dart
  packages/share_plus/share_plus/lib/src/share_plus_linux.dart
  packages/share_plus/share_plus/lib/src/share_plus_macos.dart
  packages/share_plus/share_plus/lib/src/share_plus_web.dart
  packages/share_plus/share_plus/lib/src/share_plus_windows.dart
  packages/share_plus/share_plus/lib/src/windows_version_helper.dart
  packages/share_plus/share_plus/macos/Classes/SharePlusMacosPlugin.swift
  packages/share_plus/share_plus/macos/share_plus.podspec
  packages/share_plus/share_plus/pubspec.yaml
  packages/share_plus/share_plus/test/share_plus_linux_test.dart
  packages/share_plus/share_plus/test/share_plus_windows_test.dart
  packages/share_plus/share_plus/windows/.gitignore
  packages/share_plus/share_plus/windows/CMakeLists.txt
  packages/share_plus/share_plus/windows/include/share_plus/share_plus_windows_plugin_c_api.h
  packages/share_plus/share_plus/windows/share_plus_plugin.cpp
  packages/share_plus/share_plus/windows/share_plus_plugin_c_api.cpp
  packages/share_plus/share_plus/windows/share_plus_windows_plugin.h
  packages/share_plus/share_plus/windows/vector.h
  packages/share_plus/share_plus_linux/.gitignore
  packages/share_plus/share_plus_linux/.metadata
  packages/share_plus/share_plus_linux/CHANGELOG.md
  packages/share_plus/share_plus_linux/LICENSE
  packages/share_plus/share_plus_linux/README.md
  packages/share_plus/share_plus_linux/pubspec.yaml
  packages/share_plus/share_plus_macos/.gitignore
  packages/share_plus/share_plus_macos/.metadata
  packages/share_plus/share_plus_macos/CHANGELOG.md
  packages/share_plus/share_plus_macos/LICENSE
  packages/share_plus/share_plus_macos/README.md
  packages/share_plus/share_plus_macos/macos/share_plus_macos.podspec
  packages/share_plus/share_plus_macos/pubspec.yaml
  packages/share_plus/share_plus_web/CHANGELOG.md
  packages/share_plus/share_plus_web/LICENSE
  packages/share_plus/share_plus_web/README.md
  packages/share_plus/share_plus_web/pubspec.yaml
  packages/share_plus/share_plus_windows/.clang-format
  packages/share_plus/share_plus_windows/.gitignore
  packages/share_plus/share_plus_windows/.metadata
  packages/share_plus/share_plus_windows/CHANGELOG.md
  packages/share_plus/share_plus_windows/LICENSE
  packages/share_plus/share_plus_windows/README.md
  packages/share_plus/share_plus_windows/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1235 refactor(network_info_plus)!: two-package federated architecture
  packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart
  packages/network_info_plus/network_info_plus/example/lib/main.dart
  packages/network_info_plus/network_info_plus/example/pubspec.yaml
  packages/network_info_plus/network_info_plus/lib/network_info_plus.dart
  packages/network_info_plus/network_info_plus/lib/src/network_info_plus_linux.dart
  packages/network_info_plus/network_info_plus/lib/src/network_info_plus_macos.dart
  packages/network_info_plus/network_info_plus/lib/src/network_info_plus_web.dart
  packages/network_info_plus/network_info_plus/lib/src/network_info_plus_windows.dart
  packages/network_info_plus/network_info_plus/macos/Classes/NetworkInfoPlusPlugin.swift
  packages/network_info_plus/network_info_plus/macos/network_info_plus.podspec
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus/test/device_info_plus_linux_test.dart
  packages/network_info_plus/network_info_plus/windows/.gitignore
  packages/network_info_plus/network_info_plus/windows/CMakeLists.txt
  packages/network_info_plus/network_info_plus/windows/include/network_info_plus/network_info.h
  packages/network_info_plus/network_info_plus/windows/include/network_info_plus/network_info_plus_windows_plugin.h
  packages/network_info_plus/network_info_plus/windows/network_info.cpp
  packages/network_info_plus/network_info_plus/windows/network_info_plus_plugin.cpp
  packages/network_info_plus/network_info_plus_linux/.gitignore
  packages/network_info_plus/network_info_plus_linux/.metadata
  packages/network_info_plus/network_info_plus_linux/CHANGELOG.md
  packages/network_info_plus/network_info_plus_linux/LICENSE
  packages/network_info_plus/network_info_plus_linux/README.md
  packages/network_info_plus/network_info_plus_linux/lib/network_info_plus_linux.dart
  packages/network_info_plus/network_info_plus_linux/pubspec.yaml
  packages/network_info_plus/network_info_plus_macos/.gitattributes
  packages/network_info_plus/network_info_plus_macos/.gitignore
  packages/network_info_plus/network_info_plus_macos/CHANGELOG.md
  packages/network_info_plus/network_info_plus_macos/LICENSE
  packages/network_info_plus/network_info_plus_macos/README.md
  packages/network_info_plus/network_info_plus_macos/macos/network_info_plus_macos.podspec
  packages/network_info_plus/network_info_plus_macos/pubspec.yaml
  packages/network_info_plus/network_info_plus_web/.gitattributes
  packages/network_info_plus/network_info_plus_web/.gitignore
  packages/network_info_plus/network_info_plus_web/.metadata
  packages/network_info_plus/network_info_plus_web/CHANGELOG.md
  packages/network_info_plus/network_info_plus_web/LICENSE
  packages/network_info_plus/network_info_plus_web/README.md
  packages/network_info_plus/network_info_plus_web/pubspec.yaml
  packages/network_info_plus/network_info_plus_windows/.gitignore
  packages/network_info_plus/network_info_plus_windows/.metadata
  packages/network_info_plus/network_info_plus_windows/CHANGELOG.md
  packages/network_info_plus/network_info_plus_windows/LICENSE
  packages/network_info_plus/network_info_plus_windows/README.md
  packages/network_info_plus/network_info_plus_windows/pubspec.yaml
Labels: Hacktoberfest, hacktoberfest-accepted

#1242 test(device_info_plus): Add Android display metrics check, fix Android version check
  packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
Labels: device_info_plus

#1243 docs(device_info_plus): Add info about Android properties availability, update API docs links
  docs/device_info_plus/overview.mdx
  docs/device_info_plus/usage.mdx
  packages/device_info_plus/device_info_plus/README.md
  packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
Labels: documentation, device_info_plus

#1245 refactor(device_info_plus): Migrate Android part to Kotlin, update Android dependencies
  packages/device_info_plus/device_info_plus/android/build.gradle
  packages/device_info_plus/device_info_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java
  packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
  packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.kt
  packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt
  packages/device_info_plus/device_info_plus/example/android/app/build.gradle
  packages/device_info_plus/device_info_plus/example/android/build.gradle
  packages/device_info_plus/device_info_plus/example/android/gradle.properties
  packages/device_info_plus/device_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: Hacktoberfest, hacktoberfest-accepted

#1247 docs(sensors_plus): Update website docs and README
  docs/sensors_plus/overview.mdx
  docs/sensors_plus/usage.mdx
  packages/sensors_plus/sensors_plus/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#1246 refactor(device_info_plus)!: Change nullability for AndroidDeviceInfo properties
  packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
  packages/device_info_plus/device_info_plus_platform_interface/lib/model/web_browser_info.dart
  packages/device_info_plus/device_info_plus_platform_interface/test/method_channel_device_info_test.dart
  packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_fake.dart
  packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_test.dart
Labels: device_info_plus, Hacktoberfest, hacktoberfest-accepted

#1261 chore(share_plus): Update Kotlin, Gradle and add Dependabot config
  .github/dependabot.yml
  packages/share_plus/share_plus/android/build.gradle
  packages/share_plus/share_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/share_plus/share_plus/example/android/build.gradle
  packages/share_plus/share_plus/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: share_plus, CI/CD

#1268 chore(device_info_plus): Update Kotlin, Gradle and add Dependabot config
  .github/dependabot.yml
  packages/device_info_plus/device_info_plus/android/build.gradle
  packages/device_info_plus/device_info_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/device_info_plus/device_info_plus/example/android/build.gradle
  packages/device_info_plus/device_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: device_info_plus, CI/CD

#1269 chore(battery_plus): Update Kotlin, Gradle and add Dependabot config
  .github/dependabot.yml
  packages/battery_plus/battery_plus/android/build.gradle
  packages/battery_plus/battery_plus/android/gradle/wrapper/gradle-wrapper.properties
  packages/battery_plus/battery_plus/example/android/build.gradle
Labels: battery_plus, CI/CD

#1267 chore(network_info_plus): Update Kotlin, Gradle and add Dependabot config
  .github/dependabot.yml
  packages/network_info_plus/network_info_plus/android/build.gradle
  packages/network_info_plus/network_info_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/network_info_plus/network_info_plus/example/android/build.gradle
Labels: network_info_plus

#1275 fix(all): Increase min Flutter version to fix dartPluginClass registration
  packages/battery_plus/battery_plus/pubspec.yaml
  packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
  packages/connectivity_plus/connectivity_plus/pubspec.yaml
  packages/connectivity_plus/connectivity_plus_platform_interface/pubspec.yaml
  packages/device_info_plus/device_info_plus/pubspec.yaml
  packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
  packages/network_info_plus/network_info_plus/pubspec.yaml
  packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
  packages/package_info_plus/package_info_plus/pubspec.yaml
  packages/package_info_plus/package_info_plus_platform_interface/pubspec.yaml
  packages/sensors_plus/sensors_plus/example/pubspec.yaml
  packages/sensors_plus/sensors_plus/pubspec.yaml
  packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus/pubspec.yaml
  packages/share_plus/share_plus_platform_interface/pubspec.yaml
Labels: hacktoberfest-accepted

#1284 feat(share_plus): share XFile created using File.fromData()
  packages/share_plus/share_plus/example/assets/flutter_logo.png
  packages/share_plus/share_plus/example/integration_test/share_plus_test.dart
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/example/pubspec.yaml
  packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
  packages/share_plus/share_plus_platform_interface/pubspec.yaml
  packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1302 ci(all): Skip required features if no code changed
  .github/workflows/all_plugins_skipper.yaml
Labels: CI/CD, Hacktoberfest, hacktoberfest-accepted

#1305 fix(workflows): run apt-get update before install
  .github/workflows/connectivity_plus.yaml
  .github/workflows/scripts/build-examples.sh
  .github/workflows/scripts/integration-test.sh
Labels: Hacktoberfest, hacktoberfest-accepted

#1301 fix(share_plus): return correct share result on android
  packages/share_plus/share_plus/android/src/main/AndroidManifest.xml
  packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt
  packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt
  packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt
  packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt
  packages/share_plus/share_plus/android/src/main/res/xml/flutter_share_file_paths.xml
Labels: Hacktoberfest, hacktoberfest-accepted

#1295 feat(share_plus): remove direct dependence of url_launcher
  packages/share_plus/share_plus/lib/src/share_plus_linux.dart
  packages/share_plus/share_plus/lib/src/share_plus_web.dart
  packages/share_plus/share_plus/lib/src/share_plus_windows.dart
  packages/share_plus/share_plus/pubspec.yaml
  packages/share_plus/share_plus/test/share_plus_linux_test.dart
  packages/share_plus/share_plus/test/share_plus_windows_test.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#1306 test(connectivity_plus): Fix integration test on Android 5
  packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
Labels: connectivity_plus, Hacktoberfest, hacktoberfest-accepted

#1308 ci(website): Add condition to allow access to secrets for PRs from forks
  .github/workflows/build_preview_website.yaml
Labels: website, CI/CD, Hacktoberfest, hacktoberfest-accepted
