Repository fluttercommunity/plus_plugins, pull requests merged in 2024-07, with the labels that each got.

#3082 test(package_info_plus): Fix integration test for Android
  packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
  packages/package_info_plus/package_info_plus/example/pubspec.yaml
Labels: device_info_plus

#3079 feat(sensors_plus)!: add barometer support for all platforms
  README.md
  packages/sensors_plus/sensors_plus/README.md
  packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt
  packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt
  packages/sensors_plus/sensors_plus/example/ios/Runner/Info.plist
  packages/sensors_plus/sensors_plus/example/lib/main.dart
  packages/sensors_plus/sensors_plus/ios/Classes/FPPSensorsPlusPlugin.swift
  packages/sensors_plus/sensors_plus/ios/Classes/FPPStreamHandlerPlus.swift
  packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec
  packages/sensors_plus/sensors_plus/lib/sensors_plus.dart
  packages/sensors_plus/sensors_plus/lib/src/sensors.dart
  packages/sensors_plus/sensors_plus/lib/src/sensors_plus_web.dart
  packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
  packages/sensors_plus/sensors_plus/test/sensors_test.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/sensors_plus_platform_interface.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/barometer_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/method_channel_sensors.dart
  packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart
Labels: PR: needs manual testing

#3077 feat(share_plus)!: Introduce optional parameter `nameOverride` to `shareXFiles`.
  packages/share_plus/share_plus/README.md
  packages/share_plus/share_plus/example/lib/main.dart
  packages/share_plus/share_plus/lib/share_plus.dart
  packages/share_plus/share_plus/lib/src/share_plus_linux.dart
  packages/share_plus/share_plus/lib/src/share_plus_web.dart
  packages/share_plus/share_plus/lib/src/share_plus_windows.dart
  packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
  packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
Labels: PR: pending to merge

#2506 feat(sensors_plus)!: Add support for platform timestamp in event
  packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt
  packages/sensors_plus/sensors_plus/example/lib/main.dart
  packages/sensors_plus/sensors_plus/ios/Classes/FPPStreamHandlerPlus.swift
  packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
  packages/sensors_plus/sensors_plus/test/sensors_test.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/accelerometer_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/barometer_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/gyroscope_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/magnetometer_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/method_channel_sensors.dart
  packages/sensors_plus/sensors_plus_platform_interface/lib/src/user_accelerometer_event.dart
  packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart
Labels: PR: needs review, PR: needs manual testing
