Repository fluttercommunity/plus_plugins, pull requests merged in 2024-08, with the labels that each got.

#3155 fix(battery_plus): Fix crash when retrieving battery level on desktop Mac.
  packages/battery_plus/battery_plus/macos/Classes/BatteryPlusMacosPlugin.swift
Labels: PR: needs review, PR: needs manual testing

#3158 docs(battery_plus): Update plugin requirements
  packages/battery_plus/battery_plus/README.md
Labels: documentation

#3160 docs(connectivity_plus): Update plugin requirements in README
  packages/connectivity_plus/connectivity_plus/README.md
Labels: documentation

#3162 docs(device_info_plus): Update plugin requirements in README
  packages/device_info_plus/device_info_plus/README.md
Labels: documentation

#3163 docs(package_info_plus): Update plugin requirements in README
  packages/package_info_plus/package_info_plus/README.md
Labels: documentation

#3164 docs(sensors_plus): Update plugin requirements in README
  packages/sensors_plus/sensors_plus/README.md
Labels: documentation

#3175 fix(share_plus): #2910 Handle user dismissing dialog on shareUri() in web
  packages/share_plus/share_plus/lib/src/share_plus_web.dart
Labels: share_plus, web

#3179 fix(network_info_plus): Avoid usage of unsupported package:win32 versions
  packages/network_info_plus/network_info_plus/lib/src/network_info_plus_windows.dart
  packages/network_info_plus/network_info_plus/pubspec.yaml
Labels: network_info_plus

#3183 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
